name: Test
on:
  workflow_dispatch:
  pull_request:

jobs:
  check-one:
    runs-on: ubuntu-latest
    steps:
      - run: echo "done"
  check-two:
    runs-on: ubuntu-latest
    steps:
      - run: echo "done"
